name:          Placidweb by Oussema CHERNI
description:   Linux, Red Hat certifications, technology, open source & tutorials

ga_ua_code: UA-65071829-1

url:           http://www.placidweb.com
domain:        placidweb.com
port:          4040

markdown:      kramdown
permalink:     pretty
highlighter:   rouge

kramdown:
    input: GFM
    hard_wrap: false
    toc_levels: "2,3"
